name: Build libchafa

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libglib2.0-dev

      - name: Build libchafa
        run: |
          make clean
          mkdir -p libs
          make libs/libchafa-linux-amd64.so
          sha256sum libs/*.so > CHECKSUMS.txt

      - name: Commit binaries
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add libs/ CHECKSUMS.txt
          git diff --staged --quiet || git commit -m "Auto-update binaries [skip ci]"
          git push
